# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :slug

# Setup
title:               'وبسایت منصور فدایی'
fa_title:            'وبسایت منصور فدایی'
tagline:             'وبسایت منصور فدایی'
description:         'وبسایت منصور فدایی'
subtitle:            'اشتراک تجربیات مهندسی ژئوتکنیک'
url:                 https://radioDaal.ir
baseurl:             ''
paginate:            5
lang:                'fa'
copyright:           "&#x2117; &amp; &#xA9; 2019"
timezone:            "Asia/Tehran"

# About/contact
author:
  name:              Arash Thr
  url:               https://arashTaher.ir
  email:             radioDaalPodcast@gmail.com

# Custom vars
version:             1.0.0

plugins:
    - jekyll-paginate
    - jalalidate

# Front Matter Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      excerpt_separator: <!-- more -->
